### ISSUE TITLE
Hanging on splash screen

### ISSUE THREAD

**Issue by keeganstreet** [Adobe-Marketing-Cloud-Apps/aem-phonegap-starter-kit#16]
Hi,

I have just followed the installation instructions today, however when I launch the app (using the iOS simulator), it just gets stuck on the "Apache Cordova - Device is Ready" screen. It never displays the homepage. If I inspect in Safari, I can see that the device is displaying `ShapesCon.app/www/index.html`, and it has successfully loaded index.css, cordova.js, index.js and logo.png but there has been a 404 error on loading cordova_plugins.js

Any ideas on what's going wrong here?

Cheers,
Keegan

**Comment by blefebvre** [comment]
Hi Keegan,

Can you try resetting the iOS Simulator and running the app again from the Cordova CLI? Sounds like the app id might be in conflict with another app that was installed previously.

**Comment by keeganstreet** [comment]
Hi Bruce,

Its still not running in the iOS Simulator but perhaps this is due to some other issue on my system. It is building correctly to the Android Emulator, so that is good enough for my purposes. I just needed to test out this starter kit on any platform.

Cheers,
Keegan

**Comment by keeganstreet** [comment]
Hi Bruce,

Not related to this issue, but I was wondering if Adobe have created a demo/starter kit for Angular being used together with AEM, but without Phonegap? I have had a look through the Adobe-Marketing-Cloud-Apps and they all seem to use Phonegap with content updates being deployed as OTA updates. But I would like to see an Angular Single Page App running in the web browser serving content live from AEM.

Thanks,
Keegan

**Comment by blefebvre** [comment]
Hey Keegan,

There is no Angular starter-kit for sites that I know of. That said, with a few small changes (namely, removing the reference to cordova.js) you can always activate your app to a publish instance to see how an Angular app backed by AEM would work in a browser.

Also worth noting: since we moved away from CSS transitions to the NativePageTransitions plugin, the pages will not appear to transition as smoothly when accessed via a publish instance. This can be worked around fairly easily by including Angular's ng-animate module. See [0] for details.

Regards,
Bruce

[0] https://docs.angularjs.org/api/ngAnimate
